export default {
	SET_SEARCH_FILM: 'SET_SEARCH_FILM',
	SEARCH_STARTED: 'SEARCH_STARTED',
	SEARCH_SUCCESS: 'SEARCH_SUCCESS',
	SINGLE_SEARCH_SUCCESS: 'SINGLE_SEARCH_SUCCESS',
	SEARCH_FAILURE: 'SEARCH_FAILURE',
	MOCK_FOR_SERVER_HELPER: 'MOCK_FOR_SERVER_HELPER',
};
